val activity_dot_svg : string
val corner_down_left_dot_svg : string
val link_dot_svg : string
val shopping_bag_dot_svg : string
val airplay_dot_svg : string
val corner_down_right_dot_svg : string
val list_dot_svg : string
val shopping_cart_dot_svg : string
val alert_circle_dot_svg : string
val corner_left_down_dot_svg : string
val loader_dot_svg : string
val shuffle_dot_svg : string
val alert_octagon_dot_svg : string
val corner_left_up_dot_svg : string
val lock_dot_svg : string
val sidebar_dot_svg : string
val alert_triangle_dot_svg : string
val corner_right_down_dot_svg : string
val log_in_dot_svg : string
val skip_back_dot_svg : string
val align_center_dot_svg : string
val corner_right_up_dot_svg : string
val log_out_dot_svg : string
val skip_forward_dot_svg : string
val align_justify_dot_svg : string
val corner_up_left_dot_svg : string
val mail_dot_svg : string
val slack_dot_svg : string
val align_left_dot_svg : string
val corner_up_right_dot_svg : string
val map_pin_dot_svg : string
val slash_dot_svg : string
val align_right_dot_svg : string
val cpu_dot_svg : string
val map_dot_svg : string
val sliders_dot_svg : string
val anchor_dot_svg : string
val credit_card_dot_svg : string
val maximize_2_dot_svg : string
val smartphone_dot_svg : string
val aperture_dot_svg : string
val crop_dot_svg : string
val maximize_dot_svg : string
val smile_dot_svg : string
val archive_dot_svg : string
val crosshair_dot_svg : string
val meh_dot_svg : string
val speaker_dot_svg : string
val arrow_down_circle_dot_svg : string
val database_dot_svg : string
val menu_dot_svg : string
val square_dot_svg : string
val arrow_down_left_dot_svg : string
val delete_dot_svg : string
val message_circle_dot_svg : string
val star_dot_svg : string
val arrow_down_right_dot_svg : string
val disc_dot_svg : string
val message_square_dot_svg : string
val stop_circle_dot_svg : string
val arrow_down_dot_svg : string
val divide_circle_dot_svg : string
val mic_off_dot_svg : string
val sunrise_dot_svg : string
val arrow_left_circle_dot_svg : string
val divide_square_dot_svg : string
val mic_dot_svg : string
val sunset_dot_svg : string
val arrow_left_dot_svg : string
val divide_dot_svg : string
val minimize_2_dot_svg : string
val sun_dot_svg : string
val arrow_right_circle_dot_svg : string
val dollar_sign_dot_svg : string
val minimize_dot_svg : string
val tablet_dot_svg : string
val arrow_right_dot_svg : string
val download_cloud_dot_svg : string
val minus_circle_dot_svg : string
val tag_dot_svg : string
val arrow_up_circle_dot_svg : string
val download_dot_svg : string
val minus_square_dot_svg : string
val target_dot_svg : string
val arrow_up_left_dot_svg : string
val dribbble_dot_svg : string
val minus_dot_svg : string
val terminal_dot_svg : string
val arrow_up_right_dot_svg : string
val droplet_dot_svg : string
val monitor_dot_svg : string
val thermometer_dot_svg : string
val arrow_up_dot_svg : string
val edit_2_dot_svg : string
val moon_dot_svg : string
val thumbs_down_dot_svg : string
val at_sign_dot_svg : string
val edit_3_dot_svg : string
val more_horizontal_dot_svg : string
val thumbs_up_dot_svg : string
val award_dot_svg : string
val edit_dot_svg : string
val more_vertical_dot_svg : string
val toggle_left_dot_svg : string
val bar_chart_2_dot_svg : string
val external_link_dot_svg : string
val mouse_pointer_dot_svg : string
val toggle_right_dot_svg : string
val bar_chart_dot_svg : string
val eye_off_dot_svg : string
val move_dot_svg : string
val tool_dot_svg : string
val battery_charging_dot_svg : string
val eye_dot_svg : string
val music_dot_svg : string
val trash_2_dot_svg : string
val battery_dot_svg : string
val facebook_dot_svg : string
val navigation_2_dot_svg : string
val trash_dot_svg : string
val bell_off_dot_svg : string
val fast_forward_dot_svg : string
val navigation_dot_svg : string
val trello_dot_svg : string
val bell_dot_svg : string
val feather_dot_svg : string
val octagon_dot_svg : string
val trending_down_dot_svg : string
val bluetooth_dot_svg : string
val figma_dot_svg : string
val package_dot_svg : string
val trending_up_dot_svg : string
val bold_dot_svg : string
val file_minus_dot_svg : string
val paperclip_dot_svg : string
val triangle_dot_svg : string
val bookmark_dot_svg : string
val file_plus_dot_svg : string
val pause_circle_dot_svg : string
val truck_dot_svg : string
val book_open_dot_svg : string
val file_dot_svg : string
val pause_dot_svg : string
val tv_dot_svg : string
val book_dot_svg : string
val file_text_dot_svg : string
val pen_tool_dot_svg : string
val twitch_dot_svg : string
val box_dot_svg : string
val film_dot_svg : string
val percent_dot_svg : string
val twitter_dot_svg : string
val briefcase_dot_svg : string
val filter_dot_svg : string
val phone_call_dot_svg : string
val type_dot_svg : string
val calendar_dot_svg : string
val flag_dot_svg : string
val phone_forwarded_dot_svg : string
val umbrella_dot_svg : string
val camera_off_dot_svg : string
val folder_minus_dot_svg : string
val phone_incoming_dot_svg : string
val underline_dot_svg : string
val camera_dot_svg : string
val folder_plus_dot_svg : string
val phone_missed_dot_svg : string
val unlock_dot_svg : string
val cast_dot_svg : string
val folder_dot_svg : string
val phone_off_dot_svg : string
val upload_cloud_dot_svg : string
val check_circle_dot_svg : string
val framer_dot_svg : string
val phone_outgoing_dot_svg : string
val upload_dot_svg : string
val check_square_dot_svg : string
val frown_dot_svg : string
val phone_dot_svg : string
val user_check_dot_svg : string
val check_dot_svg : string
val gift_dot_svg : string
val pie_chart_dot_svg : string
val user_minus_dot_svg : string
val chevron_down_dot_svg : string
val git_branch_dot_svg : string
val play_circle_dot_svg : string
val user_plus_dot_svg : string
val chevron_left_dot_svg : string
val git_commit_dot_svg : string
val play_dot_svg : string
val users_dot_svg : string
val chevron_right_dot_svg : string
val github_dot_svg : string
val plus_circle_dot_svg : string
val user_dot_svg : string
val chevrons_down_dot_svg : string
val gitlab_dot_svg : string
val plus_square_dot_svg : string
val user_x_dot_svg : string
val chevrons_left_dot_svg : string
val git_merge_dot_svg : string
val plus_dot_svg : string
val video_off_dot_svg : string
val chevrons_right_dot_svg : string
val git_pull_request_dot_svg : string
val pocket_dot_svg : string
val video_dot_svg : string
val chevrons_up_dot_svg : string
val globe_dot_svg : string
val power_dot_svg : string
val voicemail_dot_svg : string
val chevron_up_dot_svg : string
val grid_dot_svg : string
val printer_dot_svg : string
val volume_1_dot_svg : string
val chrome_dot_svg : string
val hard_drive_dot_svg : string
val radio_dot_svg : string
val volume_2_dot_svg : string
val circle_dot_svg : string
val hash_dot_svg : string
val refresh_ccw_dot_svg : string
val volume_dot_svg : string
val clipboard_dot_svg : string
val headphones_dot_svg : string
val refresh_cw_dot_svg : string
val volume_x_dot_svg : string
val clock_dot_svg : string
val heart_dot_svg : string
val repeat_dot_svg : string
val watch_dot_svg : string
val cloud_drizzle_dot_svg : string
val help_circle_dot_svg : string
val rewind_dot_svg : string
val wifi_off_dot_svg : string
val cloud_lightning_dot_svg : string
val hexagon_dot_svg : string
val rotate_ccw_dot_svg : string
val wifi_dot_svg : string
val cloud_off_dot_svg : string
val home_dot_svg : string
val rotate_cw_dot_svg : string
val wind_dot_svg : string
val cloud_rain_dot_svg : string
val image_dot_svg : string
val rss_dot_svg : string
val x_circle_dot_svg : string
val cloud_snow_dot_svg : string
val inbox_dot_svg : string
val save_dot_svg : string
val x_octagon_dot_svg : string
val cloud_dot_svg : string
val info_dot_svg : string
val scissors_dot_svg : string
val x_square_dot_svg : string
val codepen_dot_svg : string
val instagram_dot_svg : string
val search_dot_svg : string
val x_dot_svg : string
val codesandbox_dot_svg : string
val italic_dot_svg : string
val send_dot_svg : string
val youtube_dot_svg : string
val code_dot_svg : string
val key_dot_svg : string
val server_dot_svg : string
val zap_off_dot_svg : string
val coffee_dot_svg : string
val layers_dot_svg : string
val settings_dot_svg : string
val zap_dot_svg : string
val columns_dot_svg : string
val layout_dot_svg : string
val share_2_dot_svg : string
val zoom_in_dot_svg : string
val command_dot_svg : string
val life_buoy_dot_svg : string
val share_dot_svg : string
val zoom_out_dot_svg : string
val compass_dot_svg : string
val link_2_dot_svg : string
val shield_off_dot_svg : string
val copy_dot_svg : string
val linkedin_dot_svg : string
val shield_dot_svg : string
