[@@@js.dummy "!! This code has been generated by gen_js_api !!"]
[@@@ocaml.warning "-7-32-39"]

open! Core
open! Import
open Gen_js_api

type t =
  { xval : float
  ; yval : float
  ; canvasx : float
  ; canvasy : float
  ; name : string
  ; idx : int
  }

let rec t_of_js : Ojs.t -> t =
  fun (x2 : Ojs.t) ->
  { xval = Ojs.float_of_js (Ojs.get_prop_ascii x2 "xval")
  ; yval = Ojs.float_of_js (Ojs.get_prop_ascii x2 "yval")
  ; canvasx = Ojs.float_of_js (Ojs.get_prop_ascii x2 "canvasx")
  ; canvasy = Ojs.float_of_js (Ojs.get_prop_ascii x2 "canvasy")
  ; name = Ojs.string_of_js (Ojs.get_prop_ascii x2 "name")
  ; idx = Ojs.int_of_js (Ojs.get_prop_ascii x2 "idx")
  }

and t_to_js : t -> Ojs.t =
  fun (x1 : t) ->
  Ojs.obj
    [| "xval", Ojs.float_to_js x1.xval
     ; "yval", Ojs.float_to_js x1.yval
     ; "canvasx", Ojs.float_to_js x1.canvasx
     ; "canvasy", Ojs.float_to_js x1.canvasy
     ; "name", Ojs.string_to_js x1.name
     ; "idx", Ojs.int_to_js x1.idx
    |]
;;
